# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: "Installing modules in client /Frontend"
  inputs:
    command: 'install'
    workingDir: 'Frontend'
- task: CopyFiles@2
  inputs:
    Contents: |
      Frontend/dist/**
      Backend/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'release'
    publishLocation: 'Container'
- task: Npm@1
  displayName: "Installing modules in server /Backend"
  inputs:
    command: 'install'
    workingDir: 'Backend'

- task: Npm@1
  displayName: "Building modules in client /Frontend"
  inputs:
    command: 'custom'
    workingDir: 'Frontend'
    customCommand: 'run build'